version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
      - "8001:8001"
    expose:
      - "8001"
    labels:
      - autoscale_service=backend

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  autoscaler:
    build:
      context: ./autoscaler
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PROM_URL=http://prometheus:9090
      - DOCKER_IMAGE=backend
      - CPU_THRESHOLD=0.7
      - MIN_INSTANCES=1
      - MAX_INSTANCES=3
      - CHECK_INTERVAL=10

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    - GF_AUTH_DISABLE_LOGIN_FORM=true
    - GF_SERVER_DOMAIN=localhost
    - GF_SERVER_ROOT_URL=http://localhost:3000
    - GF_SECURITY_ALLOW_EMBEDDING=true
