version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: backend
    ports:
      - "5000:5000"
    labels:
      - autoscale_service=backend
      - fixed=true
    networks:
      - mynet

  load_balancer:
      build:
        context: ./load_balancer
      image: load_balancer:latest
      ports:
        - "8081:8080"
      depends_on:
        - backend
        - prometheus
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/targets:/etc/prometheus/targets
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - mynet

  autoscaler:
    build:
      context: ./autoscaler
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./prometheus/targets:/etc/prometheus/targets
    environment:
      - PROM_URL=http://prometheus:9090
      - DOCKER_IMAGE=backend
      - CPU_THRESHOLD=0.7
      - MIN_INSTANCES=0
      - MAX_INSTANCES=3
      - CHECK_INTERVAL=10
    networks:
      - mynet

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost:3001
      - GF_SECURITY_ALLOW_EMBEDDING=true
    networks:
      - mynet

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - mynet

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
