global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'flask-fixed'
    static_configs:
      - targets: ['pnu_cloud_computing-backend-1:5000']


  - job_name: 'flask-autoscaled'
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/flask.json
        refresh_interval: 10s
