APP_TITLE = "PNU Cloud Load Balancer (Async)"
DEFAULT_HEALTH_CHECK_INTERVAL = 10
PROXY_TIMEOUT_SECONDS = 10.0
CPU_TOGGLE_TIMEOUT_SECONDS = 5.0
METRICS_TIMEOUT_SECONDS = 2.0
MAX_CONNECTIONS = 1000
MAX_KEEPALIVE_CONNECTIONS = 100
